### ISSUE TITLE
Installation from pip in a virtualenv does not include binder.js

### ISSUE THREAD

**Issue by jpchavat** [amol-mandhane/htmlPy#1]
I installed htmlpy from pip inside a virtualenv but it didn't include the binder.js file in virtual_env/local/lib/python2.7/site-packages/htmlPy.
Some extra information from pip show htmlPy:

```
Metadata-Version: 1.1
Name: htmlPy
Version: 2.0.2
Summary: A wrapper around PySide's QtWebKit library which helps developer create beautiful UI with HTML5, CSS and Javascript for standalone applications.
Home-page: http://pypi.python.org/pypi/htmlPy/
Author: Amol Mandhane
Author-email: amol.mandhane@gmail.com
License: LICENSE.txt
Location: /home/user/Documents/htmlpy_prj/virtual_env/lib/python2.7/site-packages
Requires: 
```

(I don't know if here is the right place to submit this issue)

**Comment by rcdosado** [comment]
same issue with me, run in windows 7 pro., here is my error output:
Traceback (most recent call last):
  File "test3.py", line 4, in <module>
    app = htmlPy.AppGUI(title=u"htmlPy Quickstart", maximized=True)
  File "C:\dev\py\htmlPy\bin\lib\site-packages\htmlPy\app_gui.py", line 119, in **init**
    with open(script_location) as f:
IOError: [Errno 2] No such file or directory: 'C:\dev\py\htmlPy\bin\lib\site-package
s\htmlPy\binder.js'

**Comment by StdioA** [comment]
Same as above. 

I installed htmlPy from wheel via pip, but the wheel doesn't contains `binder.js`. Moreover, everything is fine when installing via source codes. Maybe there's something wrong with the **wheel building**.

**Comment by amol-mandhane** [comment]
The JS file appears to be in the package on PyPI but not being collected in wheel binding.

**Comment by amol-mandhane** [comment]
Please update the library versions with `pip install htmlPy --upgrade`
