### ISSUE TITLE
May I have the documents translated in Chinese

### ISSUE THREAD

**Issue by dimpurr** [amol-mandhane/htmlPy#11]
I forked it and started a project 'htmlPy-docs-cn' on ReadTheDocs, but always build failed.
Can you give me some advice, or I have ignored something must be set before?

In other words, what else should I do after I imported the Github Repo in the ReadTheDocs?

I'm a student from China. Hope it will not interrupt you.

**Comment by amol-mandhane** [comment]
I'm not sure if the problem is with the build. You might have to do some configuration for i18n on ReadTheDocs. Can you check if any other Chinese documents on ReadTheDocs have done any specific configuration?
