### ISSUE TITLE
Wrong data with radio button group in a form.

### ISSUE THREAD

**Issue by SchillingVolker** [amol-mandhane/htmlPy#12]
Hello,
I had the problem that option buttons in a group are not handle correctly because they have all the same name. Therefore I always got the value of the last button in the group. I do some modifications in the java script file:

Original binder.js:16-28

var form_bind = function (e) {
    e.preventDefault();
    var form = e.target || e.srcElement;
    if (form.getAttribute("data-bind") != "true")
        return true;
    var action = form.action;

```
var formdata = {};
for (var i = 0, ii = form.length; i < ii; ++i) {
    var input = form[i];
    if (input.name && input.type !== "file")
        formdata[input.name] = input.value;
}
```

Modified version:

var form_bind = function (e) {
    e.preventDefault();
    var form = e.target || e.srcElement;
    if (form.getAttribute("data-bind") != "true")
        return true;
    var action = form.action;

```
var formdata = {};
for (var i = 0, ii = form.length; i < ii; ++i) {
    var input = form[i];
    if (input.name) {
    if (input.type !== "file") {
        if (input.type !== "radio") {
                formdata[input.name] = input.value;
        } else {
            if (input.checked == true) {
                                formdata[input.name] = input.value;
            }
        }
    }
}
```

Mybe this is not the best solution but maybe someone could fix this issue.

Thanks,
Volker

**Comment by Waro1234** [comment]
Is there any update regarding this issue?
