### ISSUE TITLE
High Resolution Screen makes everything tiny

### ISSUE THREAD

**Issue by colmex** [amol-mandhane/htmlPy#13]
![image](https://cloud.githubusercontent.com/assets/5055015/16087257/5ecc03da-32f0-11e6-8b20-35724b1a2c2d.png)

I have a high resolution screen (3200X1800 px) and while I had to change some settings in chrome to make things scale up, with htmlPy I couldn't find how to do it?

I'm not sure if this is an issue with htmlPy or with bootstrap?

**Comment by amol-mandhane** [comment]
This is more of a bootstrap problem that htmlPy.

**Comment by colmex** [comment]
it isn't a bootstrap problem though, any library makes it tiny, I don't have this problem with bootstrap on my web browser. Webbrowser scales it all up, is there any way in htmlPy to scale up?
