### ISSUE TITLE
Loading CSS/JS assets locally without template replacement

### ISSUE THREAD

**Issue by Leprosy** [amol-mandhane/htmlPy#14]
I have this header for my `index.html` template:

``` html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Testing pyreport</title>
        <link href="css/base.css" rel="stylesheet">
        <link href="css/style.css" rel="stylesheet">
        <link href="css/c3.css" rel="stylesheet">
```

The python module `test.py` is:

``` python
import htmlPy
import os

app = htmlPy.AppGUI(title=u"JUST TESTIN'", maximized=False, developer_mode=True)

app.template_path = os.path.abspath(".")
app.static_path = os.path.abspath(".")

app.template = ("index.html", {})

app.start()
```

Both `test.py`, `index.html` and the `css/` directory are in the same base path, but when I issue the `python test.py`, the HTML is rendered ok, but no styling is loaded/applied.

Is there a way to achieve this without use Jinja replacing like the docs point out? (ie `<link rel="stylesheet" href="{{ 'css/base.css'|staticfile }}">`)

**Comment by amol-mandhane** [comment]
Rendering in htmlPy is just like rendering any other webpage. You can have CSS like `<link rel="stylesheet" href="<link to CSS file>">`. The Jinja staticfile is just a utility which allows you to create local paths to your asset files. You can enter the local href directly without using the staticfile.

Local href is generally of the format `file://<absolute path to the file>`. Jinja staticfile utility creates the same.
