### ISSUE TITLE
how to debug liker the chrome console

### ISSUE THREAD

**Issue by zphiliam** [amol-mandhane/htmlPy#17]

**Comment by amol-mandhane** [comment]
[AppGui](http://htmlpy.readthedocs.io/en/master/reference.html#htmlPy.AppGUI) has a option called `developer_mode`.

**Comment by zphiliam** [comment]
thank you very much

**Comment by zphiliam** [comment]
thank you very much

**Comment by zphiliam** [comment]
How can I bind a `htmlPy.Object` in `WebAppGUI`
