### ISSUE TITLE
Can't bind Flask with htmlPy

### ISSUE THREAD

**Issue by Crackroach** [amol-mandhane/htmlPy#18]
It is complicated or impossible to acheive? There are not enough documentation to do this.

**Comment by vladimirmyshkovski** [comment]
I am also interested in this.
As used in conjunction with the flask?
We must somehow init htmlpy

**Comment by Crackroach** [comment]
The only way I was able to acheive something was when I started Flask in a different program. Even two thread was not working.

**Comment by vladimirmyshkovski** [comment]
How to connect 2 of the program? through bind ports?

Generally, it is a great idea, what you started.
Use cardinality PyQt for GUI creation in Web applications - an incredibly
cool.

If it would be possible to achieve the interaction of classes in python and
javascript on the client side - that would be something!

For python programmers it might serve as a possibility to use more code on
the python, and less on javascript.

For me personally, the client thickening trend does not seem positive.


2016-12-28 16:41 GMT+03:00 Crackroach <notifications@github.com>:

**Comment by Crackroach** [comment]
Yes i binded the port. I've used a WebAppGui like so
app = WebAppGUI('MyApp')
app.url = 'localhost:5000'

I had to use two different project so it is complicated to make a client application. I wanted to have a siple solution to create GUI with HTML in Python. htmlPy does that, but you have to work around a bit

**Comment by amol-mandhane** [comment]
I haven't used flask before. But a quick look at documentation suggests the only way to start it is `$ flask run`. You can try running the shell command from python and then start htmlPy. You might have to use multithreading or multiprocessing module.
