### ISSUE TITLE
Example code doesn't run on my machine (windows 7.pro)

### ISSUE THREAD

**Issue by rcdosado** [amol-mandhane/htmlPy#2]
the sample code on http://htmlpy.readthedocs.org/en/master/quickstart.html#standalone-application is not running on my machine, i think you forgot to place 'u' in front of string parameters for functions AppGUI and WebAppGUI. nice project btw, thanks

**Comment by StdioA** [comment]
Maybe the example code is running under Python3 :joy:

**Comment by rcdosado** [comment]
owww..havent tried that, im running 2.7, and it fixed the error somehow, i think

**Comment by amol-mandhane** [comment]
This is an error with the documentation. I'll update it.
