### ISSUE TITLE
How enable CORS for angularjs in htmlPy?

### ISSUE THREAD

**Issue by humanely** [amol-mandhane/htmlPy#21]
I am trying to make Angular SPA based GUI. The ui-view gives following error. Is there a way to allows CORS?

`XMLHttpRequest cannot load main.html. Cross origin requests are only supported for HTTP.`

**Comment by amol-mandhane** [comment]
http://htmlpy.readthedocs.io/en/master/reference.html#AppGUI.web_app

htmlPy exposes the underlying QT objects. You can set properties for those to enable cross-origin requests.

https://pyside.github.io/docs/pyside/PySide/QtWebKit/QWebSecurityOrigin.html#PySide.QtWebKit.PySide.QtWebKit.QWebSecurityOrigin.allOrigins
