### ISSUE TITLE
Frameless fullscreen ?

### ISSUE THREAD

**Issue by quentinbodinier** [amol-mandhane/htmlPy#22]
Hello, 

Thank you for this module, it is really great and speeded up my GUI dev time by a LOT. 

I just have one problem : how could I obtain a frameless fullscreen window ? I understand this is possible in pure PySide and QT but I am not sure how this translates to htmlPy.

Thanks a lot for any clue you might have and thanks again for this great module !

**Comment by scheckmedia** [comment]
Try the following lines, this works for me: 
```python
app = htmlPy.AppGUI(title=u"Application", maximized=True)
app.window.setWindowFlags(QtCore.Qt.FramelessWindowHint)
```

**Comment by amol-mandhane** [comment]
htmlPy exposes the underlying QT objects. http://htmlpy.readthedocs.io/en/master/reference.html#AppGUI.window

You can try setting properties for those to get fullscreen. The answer recommended above should work.
