### ISSUE TITLE
JPEG Not loading

### ISSUE THREAD

**Issue by Genora51** [amol-mandhane/htmlPy#25]
I am currently making an application using HtmlPy's AppGui, when I realised that a Jpeg file I had included in my html file was not loading, and instead showing as a blue question mark. I noticed that all PNG and SVG files seemed to be working correctly, and that only JPEGs would not load. To test this (and see if the problem was with my code) I adapted one of the `Quickstart Tutorials` found on the docs, replacing the URL with that of a google images search for the word JPEG.

    import htmlPy
    web_app = htmlPy.WebAppGUI(title=u"Python Website", maximized=True)
    web_app.url = u"https://www.google.com/search?tbm=isch&q=jpeg"
    web_app.start()

Here's the result of that URL (`https://www.google.com/search?tbm=isch&q=jpeg`) from my Chrome browser:

![jpeg1](https://cloud.githubusercontent.com/assets/19515086/24080747/f6d99508-0c9c-11e7-8ffb-3c72812daeb9.PNG)

And from HtmlPy:

![jpeg2](https://cloud.githubusercontent.com/assets/19515086/24080753/0597a26a-0c9d-11e7-9ba5-557684ab25ab.PNG)

I have no idea how to resolve this, and I would be grateful if someone could find a solution, as it is quite important to my project (and presumably many others).

**Comment by rikoz** [comment]
I have same problem too, please how can it be fixed??
