### ISSUE TITLE
htmlPy with PySide2

### ISSUE THREAD

**Issue by WebTiger89** [amol-mandhane/htmlPy#26]
Hi,
is there a way to use htmlPy with PySide2. I'm asking because I use python 3.6 and the latest PySide release has at least 3.5 support or did i miss something?

**Comment by SnowWalkerJ** [comment]
I' facing the same problem as well.

**Comment by awesome-arjun11** [comment]
@Trolleule @SnowWalkerJ. You can get PySide for Python 3.6 at [Here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyside) and use pip to install. It's unofficial but worked for me without any issue yet.

**Comment by SnowWalkerJ** [comment]
Also, on ubuntu you can use `apt install python3-pyside` to install Python3-compatible PySide.

**Comment by daren-thomas** [comment]
I'm interested in an upgrade since the QtWebKit in PySide 1.2.4 doesn't support flexgrid (as far as i can tell) that is used by bootstrap...

**Comment by umeacademy** [comment]
+1 for PySide2 support please... :)

**Comment by loonghao** [comment]
How about upgrade support use `Qt.py`  ?
https://github.com/mottosso/Qt.py

**Comment by shayneoneill** [comment]
Last commit 3 years ago. Sadly I dont think we're ever going to see this solved. :(
