### ISSUE TITLE
Reaching out - Flexx

### ISSUE THREAD

**Issue by almarklein** [amol-mandhane/htmlPy#3]
Hi,

Interesting project! I wanted to reach out because I am working on a similar approach to realize a "web-tech-based" GUI for Python. The project is called [Flexx](https://github.com/zoofio/flexx). It differs from htmlPy in that it hides almost all CSS/JS/HTML for the user. Users can write client-code in Python, which is transpiled to JavaScript. Also it targets multiple web runtimes (including Qt Webkit). I am not sure if/how your goals overlap with mine, but if they do maybe we can consider some colaboration?

**Comment by amol-mandhane** [comment]
Hi

Lets continue the discussion off the repository. My contact details are on my [website](http://amol-mandhane.github.io/). Please contact me on the means preferable to you.
