### ISSUE TITLE
Error in samples

### ISSUE THREAD

**Issue by namitjuneja** [amol-mandhane/htmlPy#4]
In sample_web_app.py
it should be 

``` python
web_app = htmlPy.WebAppGUI(title=u"Python Website", maximized=True)
```

rather than

``` python
web_app = htmlPy.WebAppGUI(title="Python Website", maximized=True)
```

Title should be in unicode

**Comment by amol-mandhane** [comment]
@namitjuneja : Thanks. Some of the documentation errors slipped from my notice in the version upgrade.
