### ISSUE TITLE
Can't Href to Other HTML Template Pages

### ISSUE THREAD

**Issue by isaacaddis** [amol-mandhane/htmlPy#41]
I cannot navigate to other pages using the <a href = ""><./a> tag without right clicking and pressing "Open Link". Due to the circumstances of my project, I must have navigation completely performed with a normal left-click, as with a regular HTML page.

**Comment by Dramoscuello** [comment]
a href="Details.goDetails" data-bind="true">
               
</a>

In details.py =>  
@htmlPy.Slot()
def goDetails(self):
     self.app.template = ("details.html", {})
