### ISSUE TITLE
innerHTML doesn't work when executed from the python app

### ISSUE THREAD

**Issue by isaacaddis** [amol-mandhane/htmlPy#42]
This is a segment of my code:
``			message = '33'
                        app.evaluate_javascript("document.getElementById('temp').innerHTML="+message+";")
			app.evaluate_javascript("alert(document.getElementById('temp').textContent);")
``
The second line (alert) correctly displays that the innterHTML of the element should be 33, but the actual app does not physically show the message in its HTML.

Perhaps this has something to do with your representation of innerHTML?

**Comment by qahrb** [comment]
Try importing this library 
`import PySide.QtCore as q`

**Comment by qahrb** [comment]
Try adding this library to your code
`import PySide.QtCore as q`
Then add these lines after the first app.evaluate
```python
 die_time=q.QTime.currentTime().addSecs(1)
  while q.QTime.currentTime() < die_time:
        q.QCoreApplication.processEvents(q.QEventLoop.AllEvents,100)
```

**Comment by isaacaddis** [comment]
Thanks so much! I think you should merge this default into the project, because there will probably be people who will encounter the same problem in the future!

**Comment by qahrb** [comment]
You're welcome. I will try getting it merged as soon as possible.
