### ISSUE TITLE
unable to run example

### ISSUE THREAD

**Issue by fyears** [amol-mandhane/htmlPy#5]
As in http://amol-mandhane.github.io/htmlPy/ , I created three files exactly the same as the example in `hpy_test/`.

Then I ran

```
cd hpy_test
python main.py
```

I got the following error:

```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from back_end import BackEnd
  File "hpy_test/back_end.py", line 2, in <module>
    from main import app
  File "hpy_test/main.py", line 2, in <module>
    from back_end import BackEnd
ImportError: cannot import name BackEnd
```

And if I ran

```
# cd hpy_test
python back_end.py
```

I got the following error:

```
Traceback (most recent call last):
  File "back_end.py", line 2, in <module>
    from main import app
  File "hpy_test/main.py", line 2, in <module>
    from back_end import BackEnd
  File "hpy_test/back_end.py", line 2, in <module>
    from main import app
ImportError: cannot import name app
```

I am using python 2.7 (64bit), pyside 1.2.1 and htmlpy 2.0.3 in 64 bit windows 10.

**Comment by amol-mandhane** [comment]
For some reason, the circular imports are creating problems on Windows machine. The app seems to be working fine on linux. I'll refine the code.

**Comment by amol-mandhane** [comment]
I've adjusted the code to delay circular imports. Thanks for pointing the issue out.

**Comment by fyears** [comment]
Hi, now I could run the example, but it comes another issue.

The pop-up window shows "click here to say hello world". When I click it, I see the following error in terminal:

```
TypeError: say_hello_world() takes no arguments (1 given)
```

**Comment by amol-mandhane** [comment]
That's a silly mistake on my part. htmlPy is well tested but its documentation is not. :cry: :cry:

Should be fixed within an hour.
EDIT: fixed.

**Comment by fyears** [comment]
Yet another follow-up issue... (seriously?! :-/ )

After I clicked "click to say hello world", I saw the following error in terminal:

```
Traceback (most recent call last):
  File "hpy_test\back_end.py", line 8, in say_hello_world
    from main import app
  File "hpy_test\main.py", line 5, in <module>
    title=u"Sample application")
  File "~\venv\lib\site-packages\htmlPy\app_gui.py", line 103, in __init__
    super(AppGUI, self).__init__(*args, **kwargs)
  File "~\venv\lib\site-packages\htmlPy\base_gui.py", line 76, in __init__
    raise RuntimeError("Another htmlPy application is already running")
RuntimeError: Another htmlPy application is already running
```

I restarted the computer and init the `main.py` again and got the same error.

**Comment by amol-mandhane** [comment]
The example on the website is cooked up very quickly. I'll replace it with a proper one.

Meanwhile, you can try the ones written in the docs. I've tested them properly.

http://htmlpy.readthedocs.org/

**Comment by cosme12** [comment]
I must be doing something wrong but I cant make the examples work either (same error `RuntimeError: Another htmlPy application is already running`)

Im using "sample driver file" as the sample_app (http://htmlpy.readthedocs.org/en/master/important.html#use-a-driver-file) and GUI to python calls as the back-end function container (http://htmlpy.readthedocs.org/en/master/tutorials.html#gui-to-python-calls).

I have tried thousand of combinations but there is no way I can import the "app" var without getting this error. All functions work until I try to call "app". 
Hope you can spot my error, thanks.

**Comment by alexlib** [comment]
Is it possible to add an example of embedded matplotlib figure in hmtlPy?

**Comment by amol-mandhane** [comment]
Updated the example.
